project_id = "infidoobhmjzxlzjymuo"

[functions.send-contact-email]
verify_jwt = false

[functions.send-booking-email]
verify_jwt = false

[functions.subscribe-newsletter]
verify_jwt = false

[functions.ghl-contact-sync]
verify_jwt = false

[functions.ghl-calendar-availability]
verify_jwt = false

[functions.admin-get-data]
verify_jwt = false

[functions.admin-sync-contacts]
verify_jwt = false

[functions.admin-sync-bookings]
verify_jwt = false
