// AUTO-GENERATED from HVAC discovery questionnaire HTML.
import type { FormSchema } from "./types";
export const field_technicianSchema: FormSchema = {
  key: "field_technician",
  title: "Field Technician",
  subtitle: "For field technicians, foremen, and installers who perform on-site work.",
  sections: [
    { title: "Respondent Information", questions: [
      { title: "Name", fields: [ { name: "respondent_name", type: "text" } ] },
      { title: "Role / Title", fields: [ { name: "respondent_role", type: "text" } ] },
      { title: "Date", fields: [ { name: "response_date", type: "date" } ] },
      { title: "Years with Company", fields: [ { name: "years_with_company", type: "number" } ] },
    ] },
    { title: "1. Work Assignment and Daily Routine", questions: [
      { title: "How often do you work on more than one job in the same day?", fields: [ { name: "multi_job_frequency", type: "radio", options: [{ value: "never", label: "Never" }, { value: "rarely", label: "Rarely" }, { value: "weekly", label: "About once a week" }, { value: "several_week", label: "Several times per week" }, { value: "daily", label: "Almost daily" }] } ] },
      { title: "Who normally directs your work?", fields: [ { name: "work_direction", type: "radio", options: [{ value: "owner", label: "Owner / project manager" }, { value: "foreman", label: "Foreman" }, { value: "lead_tech", label: "Lead technician" }, { value: "self", label: "I manage my own assignments" }, { value: "varies", label: "It varies" }] } ] },
      { title: "How do you usually learn where to report and what work to perform?", fields: [ { name: "assignment_method", type: "checkbox", options: [{ value: "phone", label: "Phone call" }, { value: "text", label: "Text message" }, { value: "email", label: "Email" }, { value: "calendar", label: "Shared calendar" }, { value: "app", label: "Mobile app" }, { value: "verbal", label: "Verbal instruction" }] } ] },
    ] },
    { title: "2. Time Entry", questions: [
      { title: "How do you currently record your time?", fields: [ { name: "current_time_method", type: "checkbox", options: [{ value: "clock_app", label: "Clock-in/out app" }, { value: "paper", label: "Paper timecard" }, { value: "text", label: "Text message" }, { value: "spreadsheet", label: "Spreadsheet" }, { value: "verbal", label: "Verbal report" }, { value: "other", label: "Other" }] } ] },
      { title: "When do you normally enter or report time?", fields: [ { name: "time_entry_timing", type: "radio", options: [{ value: "start_end", label: "At clock-in and clock-out" }, { value: "end_shift", label: "At the end of the shift" }, { value: "end_week", label: "At the end of the week" }, { value: "payroll_due", label: "When payroll is due" }, { value: "inconsistent", label: "Inconsistently" }] } ] },
      { title: "What makes time entry difficult or easy to forget?", fields: [ { name: "time_entry_difficulties", type: "checkbox", options: [{ value: "busy", label: "Too busy during the day" }, { value: "multiple_jobs", label: "Multiple jobs or categories" }, { value: "poor_signal", label: "Poor mobile signal" }, { value: "too_many_steps", label: "Too many steps" }, { value: "job_not_listed", label: "Job not listed" }, { value: "code_confusion", label: "Unsure which category to select" }, { value: "forget", label: "Simply forget" }] }, { name: "time_entry_difficulty_comments", type: "textarea", placeholder: "Add examples" } ] },
      { title: "Which time-entry approach would be easiest?", fields: [ { name: "preferred_time_entry", type: "radio", options: [{ value: "clock_job", label: "Clock in/out and select job" }, { value: "daily_total", label: "Enter total hours at end of day" }, { value: "foreman_crew", label: "Foreman enters crew time" }, { value: "review_prepopulated", label: "Review and confirm a pre-filled day" }, { value: "other", label: "Other" }] } ] },
      { title: "Would geofence reminders be helpful?", fields: [ { name: "geofence_helpful", type: "radio", options: [{ value: "yes", label: "Yes" }, { value: "maybe", label: "Maybe" }, { value: "no", label: "No" }, { value: "privacy_concern", label: "I have privacy concerns" }] } ] },
    ] },
    { title: "3. Daily Field Report", questions: [
      { title: "Who should complete the daily field report?", fields: [ { name: "daily_report_owner", type: "radio", options: [{ value: "each_technician", label: "Each technician" }, { value: "foreman", label: "Foreman" }, { value: "lead_tech", label: "Lead technician" }, { value: "shared", label: "Shared responsibility" }, { value: "not_needed", label: "Not needed" }] } ] },
      { title: "What should a daily report include?", fields: [ { name: "daily_report_fields", type: "checkbox", options: [{ value: "crew", label: "Crew present" }, { value: "hours", label: "Hours worked" }, { value: "work_completed", label: "Work completed" }, { value: "material_received", label: "Material received" }, { value: "major_material_used", label: "Major material used" }, { value: "equipment_installed", label: "Equipment installed" }, { value: "photos", label: "Photos" }, { value: "delays", label: "Delays / access problems" }, { value: "safety", label: "Safety concerns" }, { value: "change_work", label: "Potential change work" }, { value: "materials_needed", label: "Materials needed" }] } ] },
      { title: "How long should a routine report take?", fields: [ { name: "daily_report_duration", type: "radio", options: [{ value: "under_2", label: "Under 2 minutes" }, { value: "2_5", label: "2\u20135 minutes" }, { value: "5_10", label: "5\u201310 minutes" }, { value: "over_10", label: "More than 10 minutes" }] } ] },
    ] },
    { title: "4. Material Purchasing and Receiving", questions: [
      { title: "Are you authorized to purchase material?", fields: [ { name: "purchase_authority", type: "radio", options: [{ value: "yes_any", label: "Yes, as needed" }, { value: "yes_threshold", label: "Yes, below a dollar limit" }, { value: "approval", label: "Only with approval" }, { value: "no", label: "No" }] } ] },
      { title: "How do you tell the supplier which job to charge?", fields: [ { name: "supplier_job_method", type: "checkbox", options: [{ value: "job_number", label: "Job number" }, { value: "job_name", label: "Job name" }, { value: "purchase_order", label: "Purchase-order number" }, { value: "verbal", label: "Verbal instruction" }, { value: "receipt_note", label: "Write it on receipt" }, { value: "inconsistent", label: "No consistent method" }] } ] },
      { title: "What should you be required to capture after a purchase?", fields: [ { name: "purchase_capture_fields", type: "checkbox", options: [{ value: "supplier", label: "Supplier" }, { value: "job", label: "Job" }, { value: "amount", label: "Approximate amount" }, { value: "category", label: "Material category" }, { value: "receipt_photo", label: "Receipt photo" }, { value: "po", label: "Purchase order / authorization" }] } ] },
      { title: "When material arrives at a job, what should be recorded?", fields: [ { name: "delivery_capture_fields", type: "checkbox", options: [{ value: "delivery_date", label: "Delivery date" }, { value: "receiver", label: "Person receiving" }, { value: "photo", label: "Delivery photo" }, { value: "packing_slip", label: "Packing slip" }, { value: "shortage", label: "Missing items" }, { value: "damage", label: "Damage" }, { value: "storage_location", label: "Storage location" }] } ] },
    ] },
    { title: "5. Material Transfers, Waste, and Returns", questions: [
      { title: "How often is material moved from one job to another?", fields: [ { name: "material_transfer_frequency", type: "radio", options: [{ value: "rarely", label: "Rarely" }, { value: "monthly", label: "Monthly" }, { value: "weekly", label: "Weekly" }, { value: "several_week", label: "Several times per week" }, { value: "daily", label: "Daily" }] } ] },
      { title: "Why is material most often wasted or lost?", fields: [ { name: "material_loss_reasons", type: "checkbox", options: [{ value: "over_ordering", label: "Over-ordering" }, { value: "wrong_material", label: "Wrong material ordered" }, { value: "damage", label: "Damage" }, { value: "rework", label: "Rework" }, { value: "unrecorded_transfer", label: "Unrecorded transfer" }, { value: "unreturned_excess", label: "Excess not returned" }, { value: "poor_storage", label: "Poor storage" }, { value: "theft", label: "Theft" }, { value: "unknown", label: "Unknown" }] } ] },
      { title: "What would make it easier to record a transfer or return?", fields: [ { name: "transfer_return_helpers", type: "checkbox", options: [{ value: "scan", label: "Scan a barcode or QR code" }, { value: "photo", label: "Take a photo" }, { value: "quick_form", label: "Use a short form" }, { value: "voice_note", label: "Use a voice note" }, { value: "foreman_only", label: "Let the foreman handle it" }] } ] },
    ] },
    { title: "6. Major Equipment and Change Work", questions: [
      { title: "Which major equipment information should field staff capture?", fields: [ { name: "equipment_fields", type: "checkbox", options: [{ value: "manufacturer", label: "Manufacturer" }, { value: "model", label: "Model" }, { value: "serial", label: "Serial number" }, { value: "delivery_photo", label: "Delivery photo" }, { value: "installed_photo", label: "Installed photo" }, { value: "location", label: "Installed location" }, { value: "startup", label: "Startup status" }] } ] },
      { title: "How is extra or changed work reported today?", fields: [ { name: "change_work_method", type: "checkbox", options: [{ value: "call", label: "Phone call" }, { value: "text", label: "Text message" }, { value: "email", label: "Email" }, { value: "photo", label: "Photo" }, { value: "daily_report", label: "Daily report" }, { value: "formal", label: "Formal change request" }, { value: "not_consistent", label: "Often not documented" }] } ] },
      { title: "What should a simple change-work report include?", fields: [ { name: "change_report_fields", type: "checkbox", options: [{ value: "description", label: "Description" }, { value: "photos", label: "Photos" }, { value: "requesting_party", label: "Who requested it" }, { value: "labor_impact", label: "Expected labor impact" }, { value: "material_impact", label: "Expected material impact" }, { value: "schedule_impact", label: "Schedule impact" }] } ] },
    ] },
    { title: "7. Mobile Experience", questions: [
      { title: "Which devices do you normally use at work?", fields: [ { name: "work_devices", type: "checkbox", options: [{ value: "iphone", label: "iPhone" }, { value: "android", label: "Android phone" }, { value: "tablet", label: "Tablet" }, { value: "laptop", label: "Laptop" }, { value: "shared_device", label: "Shared device" }] } ] },
      { title: "Which mobile functions would be most useful?", fields: [ { name: "mobile_functions", type: "checkbox", options: [{ value: "clock", label: "Clock in/out" }, { value: "select_job", label: "Select job" }, { value: "photos", label: "Upload photos" }, { value: "notes", label: "Enter notes" }, { value: "materials_used", label: "Record major materials used" }, { value: "request_materials", label: "Request additional materials" }, { value: "serial_numbers", label: "Record serial numbers" }, { value: "delivery", label: "Confirm delivery" }, { value: "change_work", label: "Report extra work" }] } ] },
      { title: "What would make you avoid using the app?", fields: [ { name: "app_adoption_concerns", type: "textarea", placeholder: "Examples: too many steps, slow loading, poor signal, confusing codes, privacy concerns" } ] },
      { title: "Field technician comments and suggestions", fields: [ { name: "field_final_comments", type: "textarea" } ] },
    ] },
  ],
};