// AUTO-GENERATED from HVAC discovery questionnaire HTML.
import type { FormSchema } from "./types";
export const office_accountingSchema: FormSchema = {
  key: "office_accounting",
  title: "Office / Accounting",
  subtitle: "For office staff and accounting personnel who handle billing, payroll, and vendor bills.",
  sections: [
    { title: "Respondent Information", questions: [
      { title: "Name", fields: [ { name: "respondent_name", type: "text" } ] },
      { title: "Role / Title", fields: [ { name: "respondent_role", type: "text" } ] },
      { title: "Date", fields: [ { name: "response_date", type: "date" } ] },
      { title: "Years with Company", fields: [ { name: "years_with_company", type: "number" } ] },
    ] },
    { title: "1. Office and Accounting Responsibilities", questions: [
      { title: "Which activities are part of your role?", fields: [ { name: "office_responsibilities", type: "checkbox", options: [{ value: "project_setup", label: "Project setup" }, { value: "time_review", label: "Reviewing employee time" }, { value: "payroll", label: "Payroll coordination" }, { value: "vendor_bills", label: "Entering vendor bills" }, { value: "invoice_coding", label: "Assigning invoices to jobs" }, { value: "purchasing", label: "Purchasing" }, { value: "customer_invoicing", label: "Customer invoicing" }, { value: "quickbooks", label: "QuickBooks administration" }, { value: "files", label: "Project files and documents" }, { value: "reporting", label: "Management reports" }] } ] },
    ] },
    { title: "2. QuickBooks Online", questions: [
      { title: "Which QuickBooks features are currently used?", fields: [ { name: "qbo_features", type: "checkbox", options: [{ value: "customers", label: "Customers" }, { value: "projects", label: "Projects" }, { value: "estimates", label: "Estimates" }, { value: "invoices", label: "Invoices" }, { value: "vendor_bills", label: "Vendor bills" }, { value: "purchase_orders", label: "Purchase orders" }, { value: "time_tracking", label: "Time tracking" }, { value: "products_services", label: "Products and services" }, { value: "classes", label: "Classes" }, { value: "locations", label: "Locations" }, { value: "payroll", label: "Payroll" }, { value: "bank_feeds", label: "Bank feeds" }, { value: "attachments", label: "Attachments" }, { value: "custom_fields", label: "Custom fields" }] } ] },
      { title: "How quickly are supplier invoices entered?", fields: [ { name: "invoice_entry_speed", type: "radio", options: [{ value: "same_day", label: "Same day" }, { value: "within_3_days", label: "Within 3 days" }, { value: "weekly", label: "Weekly" }, { value: "monthly", label: "Monthly" }, { value: "statement", label: "When statements arrive" }, { value: "inconsistent", label: "Inconsistently" }] } ] },
      { title: "Are vendor bills consistently assigned to jobs?", fields: [ { name: "bills_assigned_jobs", type: "radio", options: [{ value: "always", label: "Always" }, { value: "usually", label: "Usually" }, { value: "sometimes", label: "Sometimes" }, { value: "rarely", label: "Rarely" }, { value: "unknown", label: "Unknown" }] } ] },
      { title: "Which information should flow from QuickBooks into the prototype?", fields: [ { name: "qbo_to_prototype", type: "checkbox", options: [{ value: "customers", label: "Customers" }, { value: "vendors", label: "Vendors" }, { value: "projects", label: "Projects" }, { value: "vendor_bills", label: "Vendor bills" }, { value: "bill_payments", label: "Bill payments" }, { value: "payroll_costs", label: "Payroll costs" }, { value: "customer_invoices", label: "Customer invoices" }, { value: "payments", label: "Customer payments" }] } ] },
      { title: "Which information may need to flow from the prototype into QuickBooks?", fields: [ { name: "prototype_to_qbo", type: "checkbox", options: [{ value: "approved_time", label: "Approved time" }, { value: "job_records", label: "Job records" }, { value: "purchase_information", label: "Purchase information" }, { value: "receipt_attachments", label: "Receipt attachments" }, { value: "cost_categories", label: "Cost categories" }, { value: "supplier_coding", label: "Approved supplier coding" }] } ] },
    ] },
    { title: "3. Time and Payroll Workflow", questions: [
      { title: "How is employee time currently received?", fields: [ { name: "time_received", type: "checkbox", options: [{ value: "quickbooks_time", label: "QuickBooks Time" }, { value: "paper", label: "Paper timecards" }, { value: "text", label: "Text messages" }, { value: "spreadsheet", label: "Spreadsheet" }, { value: "verbal", label: "Verbal report" }, { value: "other", label: "Other" }] } ] },
      { title: "How often are entries missing or late?", fields: [ { name: "late_time_frequency", type: "select", options: [{ value: "Rarely", label: "Rarely" }, { value: "Monthly", label: "Monthly" }, { value: "Weekly", label: "Weekly" }, { value: "Several times per week", label: "Several times per week" }, { value: "Almost daily", label: "Almost daily" }] } ] },
      { title: "How are corrections handled today?", fields: [ { name: "time_corrections", type: "radio", options: [{ value: "employee", label: "Employee corrects entry" }, { value: "office", label: "Office staff corrects entry" }, { value: "owner", label: "Owner corrects or approves" }, { value: "informal", label: "Informally, without documented approval" }] } ] },
      { title: "What information is required before time is ready for payroll?", fields: [ { name: "payroll_required_fields", type: "checkbox", options: [{ value: "employee", label: "Employee" }, { value: "date", label: "Date" }, { value: "job", label: "Job" }, { value: "cost_code", label: "Work category / cost code" }, { value: "regular_ot", label: "Regular or overtime" }, { value: "start_end", label: "Start and end time" }, { value: "notes", label: "Notes for exceptions" }] } ] },
    ] },
    { title: "4. Purchasing and Supplier Information", questions: [
      { title: "How are purchases associated with jobs?", fields: [ { name: "purchase_job_assignment", type: "checkbox", options: [{ value: "supplier_job_account", label: "Supplier job account" }, { value: "purchase_order", label: "Purchase-order number" }, { value: "job_name", label: "Job name" }, { value: "employee_tells_supplier", label: "Employee tells supplier" }, { value: "receipt_note", label: "Written on receipt" }, { value: "office_allocates", label: "Office allocates later" }, { value: "inconsistent", label: "No consistent method" }] } ] },
      { title: "Which supplier records are commonly available?", fields: [ { name: "supplier_records", type: "checkbox", options: [{ value: "email_invoices", label: "Emailed invoices" }, { value: "pdf", label: "PDF invoices" }, { value: "csv", label: "CSV export" }, { value: "excel", label: "Excel export" }, { value: "portal", label: "Online portal" }, { value: "monthly_statement", label: "Monthly statement" }, { value: "api", label: "API" }, { value: "unknown", label: "Unknown" }] } ] },
      { title: "What causes the most office rework?", fields: [ { name: "office_rework", type: "checkbox", options: [{ value: "missing_receipts", label: "Missing receipts" }, { value: "wrong_job", label: "Wrong job assignment" }, { value: "no_category", label: "Missing cost category" }, { value: "duplicate_entry", label: "Duplicate entry" }, { value: "late_invoice", label: "Late supplier invoice" }, { value: "time_correction", label: "Time corrections" }, { value: "missing_approval", label: "Missing approval" }] }, { name: "office_rework_comments", type: "textarea", placeholder: "Provide examples" } ] },
    ] },
    { title: "5. Material Returns and Supplier Credits", questions: [
      { title: "How are returns and credits handled today?", fields: [ { name: "returns_process", type: "checkbox", options: [{ value: "technician_returns", label: "Technician returns material" }, { value: "office_arranges", label: "Office arranges return" }, { value: "supplier_pickup", label: "Supplier pickup" }, { value: "tracked_qbo", label: "Credits tracked in QuickBooks" }, { value: "not_consistent", label: "Credits not consistently tracked" }, { value: "no_process", label: "No formal process" }] } ] },
      { title: "Should the prototype maintain a pending-credit list?", fields: [ { name: "pending_credit_list", type: "radio", options: [{ value: "yes", label: "Yes" }, { value: "no", label: "No" }, { value: "unsure", label: "Unsure" }] } ] },
    ] },
    { title: "6. Reporting and Exceptions", questions: [
      { title: "Which exceptions should appear in an office work queue?", fields: [ { name: "office_exceptions", type: "checkbox", options: [{ value: "missing_time", label: "Missing employee time" }, { value: "uncoded_purchase", label: "Purchase without a job" }, { value: "invoice_no_category", label: "Invoice without a cost category" }, { value: "delivery_unconfirmed", label: "Unconfirmed delivery" }, { value: "credit_pending", label: "Pending supplier credit" }, { value: "equipment_delay", label: "Equipment delivery delay" }, { value: "time_correction", label: "Time correction awaiting approval" }] } ] },
      { title: "What would reduce your workload most?", fields: [ { name: "office_workload_reduction", type: "textarea" } ] },
      { title: "Office/accounting comments and concerns", fields: [ { name: "office_final_comments", type: "textarea" } ] },
    ] },
  ],
};