// AUTO-GENERATED from HVAC discovery questionnaire HTML.
import type { FormSchema } from "./types";
export const owner_managementSchema: FormSchema = {
  key: "owner_management",
  title: "Owner / Management",
  subtitle: "For the owner, estimator, project manager, or senior decision-maker.",
  sections: [
    { title: "Respondent Information", questions: [
      { title: "Name", fields: [ { name: "respondent_name", type: "text" } ] },
      { title: "Role / Title", fields: [ { name: "respondent_role", type: "text" } ] },
      { title: "Date", fields: [ { name: "response_date", type: "date" } ] },
      { title: "Years with Company", fields: [ { name: "years_with_company", type: "number" } ] },
    ] },
    { title: "1. Company and Project Profile", questions: [
      { title: "Primary work performed", fields: [ { name: "primary_work", type: "checkbox", options: [{ value: "commercial_plan_spec", label: "Commercial plan-and-spec installation" }, { value: "commercial_design_build", label: "Commercial design-build installation" }, { value: "commercial_retrofit", label: "Commercial replacement / retrofit" }, { value: "commercial_service", label: "Commercial service" }, { value: "preventive_maintenance", label: "Preventive maintenance" }, { value: "government", label: "Government / public-sector work" }, { value: "other", label: "Other" }] }, { name: "primary_work_other", type: "text", placeholder: "Describe other work" } ] },
      { title: "Typical project value", fields: [ { name: "typical_project_value", type: "radio", options: [{ value: "under_100k", label: "Under $100,000" }, { value: "100_250k", label: "$100,000\u2013$250,000" }, { value: "250_500k", label: "$250,000\u2013$500,000" }, { value: "500k_1m", label: "$500,000\u2013$1 million" }, { value: "1m_5m", label: "$1 million\u2013$5 million" }, { value: "over_5m", label: "Above $5 million" }] } ] },
      { title: "Typical number of active projects", fields: [ { name: "active_projects", type: "select", options: [{ value: "1\u20133", label: "1\u20133" }, { value: "4\u20136", label: "4\u20136" }, { value: "7\u201310", label: "7\u201310" }, { value: "More than 10", label: "More than 10" }] } ] },
      { title: "Typical project duration", fields: [ { name: "project_duration", type: "select", options: [{ value: "Under 1 month", label: "Under 1 month" }, { value: "1\u20133 months", label: "1\u20133 months" }, { value: "3\u20136 months", label: "3\u20136 months" }, { value: "6\u201312 months", label: "6\u201312 months" }, { value: "More than 12 months", label: "More than 12 months" }] } ] },
    ] },
    { title: "2. Business Priorities and Pain Points", questions: [
      { title: "Select the five most important business priorities", fields: [ { name: "business_priorities", type: "checkbox", options: [{ value: "profitability", label: "Improve profitability" }, { value: "job_costing", label: "Better job costing" }, { value: "material_control", label: "Reduce material loss or waste" }, { value: "time_capture", label: "Improve labor time capture" }, { value: "reporting", label: "Better management reporting" }, { value: "invoicing", label: "Faster invoicing" }, { value: "change_orders", label: "Better change-order documentation" }, { value: "paperwork", label: "Reduce paperwork" }, { value: "growth", label: "Prepare the company for growth" }] } ] },
      { title: "What are the three biggest reasons jobs lose money today?", fields: [ { name: "loss_causes", type: "checkbox", options: [{ value: "labor_overrun", label: "Labor overruns" }, { value: "material_overrun", label: "Material overruns" }, { value: "scope_changes", label: "Scope changes / extra work" }, { value: "estimating", label: "Estimating errors" }, { value: "delays", label: "Scheduling or access delays" }, { value: "rework", label: "Rework" }, { value: "poor_coding", label: "Purchases not assigned to the correct job" }, { value: "unknown", label: "Unknown until project completion" }] }, { name: "loss_causes_comments", type: "textarea", placeholder: "Explain examples from recent jobs" } ] },
    ] },
    { title: "3. Estimating and Budgeting", questions: [
      { title: "How are estimates prepared?", fields: [ { name: "estimate_method", type: "checkbox", options: [{ value: "spreadsheet", label: "Spreadsheet" }, { value: "quickbooks", label: "QuickBooks estimate" }, { value: "estimating_software", label: "Estimating software" }, { value: "manual", label: "Manual calculations" }, { value: "supplier_quotes", label: "Supplier quotations" }] } ] },
      { title: "Which estimate categories are currently used?", fields: [ { name: "estimate_categories", type: "checkbox", options: [{ value: "labor", label: "Labor" }, { value: "equipment", label: "Equipment" }, { value: "ductwork", label: "Ductwork" }, { value: "piping", label: "Piping" }, { value: "controls", label: "Controls" }, { value: "subcontractors", label: "Subcontractors" }, { value: "rentals", label: "Equipment rentals" }, { value: "permits", label: "Permits" }, { value: "freight", label: "Freight" }, { value: "contingency", label: "Contingency" }] } ] },
      { title: "Does the estimate include labor hours?", fields: [ { name: "estimate_labor_hours", type: "radio", options: [{ value: "by_category", label: "Yes, by major category" }, { value: "project_total", label: "Yes, as one project total" }, { value: "sometimes", label: "Sometimes" }, { value: "no", label: "No" }] } ] },
      { title: "When a project is awarded, how is the operating budget created?", fields: [ { name: "budget_creation", type: "radio", options: [{ value: "estimate_becomes_budget", label: "Estimate becomes the budget" }, { value: "separate_owner_budget", label: "Owner creates a separate budget" }, { value: "office_reentry", label: "Office staff re-enters the information" }, { value: "quickbooks_project", label: "QuickBooks project is used" }, { value: "none", label: "No formal project budget is created" }] } ] },
      { title: "Should the original budget always be preserved?", fields: [ { name: "preserve_budget", type: "radio", options: [{ value: "yes", label: "Yes; preserve original and track approved revisions separately" }, { value: "replace", label: "Replace the original budget when revised" }, { value: "unsure", label: "Unsure" }] } ] },
    ] },
    { title: "4. Job Lifecycle and Management Review", questions: [
      { title: "Which project stages should be formally tracked?", fields: [ { name: "job_stages", type: "checkbox", options: [{ value: "lead", label: "Lead / opportunity" }, { value: "site_visit", label: "Site visit" }, { value: "estimate", label: "Estimate" }, { value: "awarded", label: "Awarded" }, { value: "contract", label: "Contract executed" }, { value: "budget", label: "Budget approved" }, { value: "procurement", label: "Procurement" }, { value: "mobilization", label: "Mobilization" }, { value: "active", label: "Active installation" }, { value: "startup", label: "Testing / startup" }, { value: "punch", label: "Punch list" }, { value: "substantial_completion", label: "Substantial completion" }, { value: "final_billing", label: "Final billing" }, { value: "warranty", label: "Warranty" }, { value: "closed", label: "Closed" }] } ] },
      { title: "How often should active-job profitability be reviewed?", fields: [ { name: "profit_review_frequency", type: "radio", options: [{ value: "weekly", label: "Weekly" }, { value: "biweekly", label: "Biweekly" }, { value: "monthly", label: "Monthly" }, { value: "milestone", label: "At major milestones" }, { value: "completion", label: "Only at completion" }] } ] },
      { title: "Select dashboard measures required for weekly review", fields: [ { name: "dashboard_metrics", type: "checkbox", options: [{ value: "contract_value", label: "Contract value" }, { value: "approved_changes", label: "Approved change orders" }, { value: "budget_actual", label: "Budget versus actual" }, { value: "labor_hours", label: "Labor hours budgeted versus used" }, { value: "material_committed", label: "Material committed" }, { value: "material_invoiced", label: "Material invoiced" }, { value: "percent_complete", label: "Percent complete" }, { value: "cost_to_complete", label: "Forecast cost to complete" }, { value: "gross_profit", label: "Forecast gross profit" }, { value: "missing_time", label: "Missing time entries" }, { value: "uncoded_purchases", label: "Uncoded purchases" }, { value: "pending_credits", label: "Pending supplier credits" }, { value: "change_events", label: "Open change events" }] } ] },
    ] },
    { title: "5. Prototype Priorities and Success", questions: [
      { title: "Which prototype capabilities should be highest priority?", fields: [ { name: "prototype_priorities", type: "checkbox", options: [{ value: "job_budget", label: "Job budget setup/import" }, { value: "mobile_time", label: "Mobile labor entry" }, { value: "missing_time", label: "Missing-time alerts" }, { value: "major_equipment", label: "Major-equipment tracking" }, { value: "purchase_capture", label: "Purchase/receipt capture" }, { value: "supplier_invoice", label: "Supplier invoice import" }, { value: "material_transfer", label: "Material transfers" }, { value: "supplier_credits", label: "Supplier credits" }, { value: "change_events", label: "Change-event tracking" }, { value: "quickbooks", label: "QuickBooks integration" }, { value: "dashboard", label: "Owner dashboard" }] } ] },
      { title: "What would make the 90-day prototype successful?", fields: [ { name: "success_criteria", type: "checkbox", options: [{ value: "95_time_next_day", label: "95% of time entered by the next business day" }, { value: "95_purchases_job", label: "95% of purchases assigned to a job" }, { value: "weekly_report", label: "Weekly job-cost report available" }, { value: "equipment_visibility", label: "Major equipment visible from order through installation" }, { value: "transfers_recorded", label: "Material transfers recorded" }, { value: "credits_visible", label: "Pending supplier credits visible" }, { value: "changes_documented", label: "Potential change work documented" }, { value: "owner_time_saved", label: "Owner saves measurable administrative time" }, { value: "early_overrun", label: "At least one overrun identified before completion" }] } ] },
      { title: "Owner comments, constraints, and concerns", fields: [ { name: "owner_final_comments", type: "textarea" } ] },
    ] },
  ],
};